### PR TITLE
ARC-1264: MVP - Split Connection Screen Workflow

### PR DESCRIPTION
**Pull request by yvonnevictoria**
**Context**
Due to a confusing Jenkins server connection flow, we have decided to split the Jenkins server connection flow into 3 steps. For more information, [see here](https://hello.atlassian.net/wiki/spaces/PF/pages/1793379128/JFA+ARC-1264+-+Split+Connection+Screen+plan+and+ideation).

**Changes in this PR**
This PR merges a MVP version of the new Jenkins server connection workflow. **This PR should only be merged in the event that changes need to be deployed before @yvonnevictoria is back from leave.**

Step 1 - Install Jenkins:
image

Step 2 - Create Server:
Input name and click "Create" to create a new server.
image

_Loading state_
image

_Error state_
image

Step 3 - Connect Server:
Retrieves newly created server details. View webhook URL and secret. Update name if desired.
image

_Loading state_
image

### CODE REVIEW

**Comment by Harminder84** [comment]
This will break the Jenkins pollinator checks. I think, you won't be able to publish unless you fix the pollnator check.

**Review by gxueatlassian — COMMENTED** [review]
Overall looks good to me. But tbh there's quite a lot of code here. I am not sure how to fully grab it before I approve it. Let me know if you can have a walkthrough of the code (and ideally with someone else in the team as well so not to waste your time).

**Comment by yvonnevictoria** [comment]
> Overall looks good to me. But tbh there's quite a lot of code here. I am not sure how to fully grab it before I approve it. Let me know if you can have a walkthrough of the code (and ideally with someone else in the team as well so not to waste your time).

@gxueatlassian All PRs were reviewed in smaller chunks before being pushed to the feature branch. This PR was set up so that if the feature needed to be merged while I was on leave, a MVP version was available to be pushed to prod.

**Comment by yvonnevictoria** [comment]
Closing this as I've returned from leave and will be continuing work on this feature 💃

**Pull request closed without merging**
